-- Phase 4: raw tables matching processed CSV schemas.
-- CREATE OR REPLACE keeps local schema definition authoritative on reruns.
-- Data reload is handled separately via TRUNCATE + COPY INTO.

USE DATABASE CIP_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS (
  CUSTOMER_ID         VARCHAR(32)   NOT NULL,
  GENDER              VARCHAR(16)   NOT NULL,
  IS_SENIOR_CITIZEN   BOOLEAN       NOT NULL,
  HAS_PARTNER         BOOLEAN       NOT NULL,
  HAS_DEPENDENTS      BOOLEAN       NOT NULL,
  IS_CHURNED          BOOLEAN       NOT NULL
);

CREATE OR REPLACE TABLE SUBSCRIPTIONS (
  CUSTOMER_ID                 VARCHAR(32)     NOT NULL,
  TENURE_MONTHS               NUMBER(38, 0)   NOT NULL,
  HAS_PHONE_SERVICE           BOOLEAN         NOT NULL,
  MULTIPLE_LINES_STATUS       VARCHAR(32)     NOT NULL,
  INTERNET_SERVICE_TYPE       VARCHAR(32)     NOT NULL,
  ONLINE_SECURITY_STATUS      VARCHAR(32)     NOT NULL,
  ONLINE_BACKUP_STATUS        VARCHAR(32)     NOT NULL,
  DEVICE_PROTECTION_STATUS    VARCHAR(32)     NOT NULL,
  TECH_SUPPORT_STATUS         VARCHAR(32)     NOT NULL,
  STREAMING_TV_STATUS         VARCHAR(32)     NOT NULL,
  STREAMING_MOVIES_STATUS     VARCHAR(32)     NOT NULL,
  CONTRACT_TYPE               VARCHAR(32)     NOT NULL,
  MONTHLY_CHARGES             NUMBER(10, 2)   NOT NULL
);

CREATE OR REPLACE TABLE BILLING (
  CUSTOMER_ID         VARCHAR(32)     NOT NULL,
  PAPERLESS_BILLING   BOOLEAN         NOT NULL,
  PAYMENT_METHOD      VARCHAR(64)     NOT NULL,
  TOTAL_CHARGES       NUMBER(12, 2)   NOT NULL
);

CREATE OR REPLACE TABLE TRANSACTIONS (
  TRANSACTION_ID      VARCHAR(64)     NOT NULL,
  CUSTOMER_ID         VARCHAR(32)     NOT NULL,
  TRANSACTION_DATE    DATE            NOT NULL,
  BILLING_PERIOD      VARCHAR(7)      NOT NULL,
  AMOUNT              NUMBER(12, 2)   NOT NULL,
  PAYMENT_METHOD      VARCHAR(64)     NOT NULL,
  PAYMENT_STATUS      VARCHAR(32)     NOT NULL,
  IS_AUTOPAY          BOOLEAN         NOT NULL
);

CREATE OR REPLACE TABLE SUPPORT_TICKETS (
  TICKET_ID                 VARCHAR(64)     NOT NULL,
  CUSTOMER_ID               VARCHAR(32)     NOT NULL,
  CREATED_AT                TIMESTAMP_NTZ   NOT NULL,
  CLOSED_AT                 TIMESTAMP_NTZ,
  ISSUE_TYPE                VARCHAR(32)     NOT NULL,
  PRIORITY                  VARCHAR(16)     NOT NULL,
  STATUS                    VARCHAR(16)     NOT NULL,
  RESOLUTION_TIME_HOURS     NUMBER(10, 2),
  SATISFACTION_SCORE        NUMBER(2, 0)
);

CREATE OR REPLACE TABLE USAGE_EVENTS (
  EVENT_ID          VARCHAR(128)    NOT NULL,
  CUSTOMER_ID       VARCHAR(32)     NOT NULL,
  EVENT_DATE        DATE            NOT NULL,
  BILLING_PERIOD    VARCHAR(7)      NOT NULL,
  EVENT_TYPE        VARCHAR(32)     NOT NULL,
  QUANTITY          FLOAT           NOT NULL,
  UNIT              VARCHAR(16)     NOT NULL
);
