-- Phase 4: load processed S3 CSVs into RAW tables (rerunnable).
-- Truncate then COPY INTO so reruns replace data without duplicates.
-- Stage URL is s3://<bucket>/processed/, so paths are relative to that prefix.

USE WAREHOUSE CIP_WH;
USE DATABASE CIP_DB;
USE SCHEMA RAW;

TRUNCATE TABLE IF EXISTS CUSTOMERS;
COPY INTO CUSTOMERS
  FROM @CIP_S3_STAGE/customers/customers.csv
  FILE_FORMAT = (FORMAT_NAME = CIP_CSV_FORMAT)
  ON_ERROR = 'ABORT_STATEMENT'
  FORCE = TRUE;

TRUNCATE TABLE IF EXISTS SUBSCRIPTIONS;
COPY INTO SUBSCRIPTIONS
  FROM @CIP_S3_STAGE/subscriptions/subscriptions.csv
  FILE_FORMAT = (FORMAT_NAME = CIP_CSV_FORMAT)
  ON_ERROR = 'ABORT_STATEMENT'
  FORCE = TRUE;

TRUNCATE TABLE IF EXISTS BILLING;
COPY INTO BILLING
  FROM @CIP_S3_STAGE/billing/billing.csv
  FILE_FORMAT = (FORMAT_NAME = CIP_CSV_FORMAT)
  ON_ERROR = 'ABORT_STATEMENT'
  FORCE = TRUE;

TRUNCATE TABLE IF EXISTS TRANSACTIONS;
COPY INTO TRANSACTIONS
  FROM @CIP_S3_STAGE/transactions/transactions.csv
  FILE_FORMAT = (FORMAT_NAME = CIP_CSV_FORMAT)
  ON_ERROR = 'ABORT_STATEMENT'
  FORCE = TRUE;

TRUNCATE TABLE IF EXISTS SUPPORT_TICKETS;
COPY INTO SUPPORT_TICKETS
  FROM @CIP_S3_STAGE/support_tickets/support_tickets.csv
  FILE_FORMAT = (FORMAT_NAME = CIP_CSV_FORMAT)
  ON_ERROR = 'ABORT_STATEMENT'
  FORCE = TRUE;

TRUNCATE TABLE IF EXISTS USAGE_EVENTS;
COPY INTO USAGE_EVENTS
  FROM @CIP_S3_STAGE/usage_events/usage_events.csv
  FILE_FORMAT = (FORMAT_NAME = CIP_CSV_FORMAT)
  ON_ERROR = 'ABORT_STATEMENT'
  FORCE = TRUE;
